server:
  port: 7002

eureka:
  instance:
    a-s-g-name: localhost # Eureka服务端的实例名字
  client:
    register-with-eureka: false # 表示是否向Eureka注册中心注册自己
    fetch-registry: false #fetch-registry为false则表示自己为注册中心
    service-url:
      # 单机 defaultZone: http://${eureka.instance.a-s-g-name}:${server.port}/eureka/
      ###集群
      defaultZone: http://localhost:7001/eureka/,http://localhost:7003/eureka/